apiVersion: v1
kind: Service
metadata:
  name: grpc-web
spec:
  selector:
    app: grpc-web
  type: ClusterIP
  ports:
  - name: http2
    protocol: TCP
    port: 9074  # no targetPort for headless service